spring.application.name=order-system





spring.datasource.url=jdbc:mysql://localhost:3306/halleyx_db
spring.datasource.username=root
spring.datasource.password=Sh@36

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect